
```{r}

library(igraph)
library(tidygraph)
library(tidyverse)
library(cowplot)
library(furrr)
library(flextable)

load(file ='HHSizes.Rdata')

degree_dist_p = HH_SizeHist_All$Count/sum(HH_SizeHist_All$Count)

sum(HH_SizeHist_All$Count)

AverageHouseholdSize = sum(HH_SizeHist_All$Count/sum(HH_SizeHist_All$Count)*HH_SizeHist_All$Size)

# =2.356

HH_SizeHist_All %>% 
  ggplot(aes(x=Size,y=Count/sum(Count)))+
  geom_point()+
  scale_x_log10()+
  scale_y_log10()+
  ylab('P(S)')+
  xlab('Household Size, S')+
  theme_minimal_grid()->p




ggsave(p,filename='HouseholdSizeDist.png',width=7,height=5)


HH_SizeHist_All %>% 
  filter(Size<11) %>% 
  flextable()

```

```{r}

HH_SizeHist_All %>% 
  mutate(NumberInternalLinks = Size-1) %>% 
  mutate(DegreeDistribution = Size*Count) %>% 
  summarise(sum(Size*DegreeDistribution/sum(DegreeDistribution)))->meanDegree



HH_SizeHist_All %>% 
  mutate(NumberInternalLinks = Size-1) %>% 
  mutate(DegreeDistribution = Size*Count) %>% 
  ggplot(aes(x=Size,y=DegreeDistribution))+
  geom_point()+
  scale_x_log10()+
  scale_y_log10()+
   ylab('P(k)')+
  xlab('Number of contacts, k')+
  theme_minimal()


```


```{r}
attackRate = 0.4
Beta = 0.48
pc=0.479
pc=seq(0,1,0.1)
PC = Beta*pc
  

```




```{r include = FALSE} 
library('moments')
sample(30, 1000, replace = TRUE, degree_dist_p)->oneK
sample(30, 10000, replace = TRUE, degree_dist_p)->tenK
sample(30, 100000, replace = TRUE, degree_dist_p)->hundredK
sample(30, 1000000, replace = TRUE, degree_dist_p)->million

as.tibble(tenK)%>% 
  group_by(value) %>% 
  summarise(N=n()) # that seems to be working then. 

HH_SizeHist_All %>% 
  ggplot()+
  geom_col(data=HH_SizeHist_All, aes(x=Size,y=Count/sum(Count)))

as.tibble(tenK)%>% 
  ggplot(aes(x=tenK))+
  geom_histogram(bins=max(tenK))




```


```{r}


N=100000
degseq=1

# make sure there are an even number of stubbs & generate a degree sequence
while(sum(degseq)%%2!=0)sample(30, N, replace = TRUE, degree_dist_p)->degseq 


nl=sum(degseq)  # number of links

nl/100000 # agrees with distribution above - PHEW

g<-sample_degseq(degseq)  #
removenumber = seq(0,nl/2,1000)  # sequence of number of edges to remove for percolation analysis


# function for performing percolation analysis by removing edges

meanmaxClusters <- function(g,i){
  sub_g<-delete_edges(g,sample(E(g),i)) # remove i edges
  compssize=components(sub_g)$csize
  MeanDegSq = mean(degree(sub_g)^2)
  Max=max(compssize)
  Mean=mean(compssize)
  SD = sd(compssize)
  Mean_woMax=mean(compssize[!compssize==max(compssize)])
  return(data.frame(Max,Mean_woMax,SD,Mean,MeanDegSq))
} 


data.frame(removenumber)%>% # iterate percolation function over the sequence of edge removals
  mutate(d=map(removenumber,~meanmaxClusters(g,.))) %>% 
  unnest(d)->tmp
  
tmp %>% summarise(pc=removenumber[which.max(Mean_woMax)])

tmp %>% 
  pivot_longer(-removenumber) %>% 
  ggplot(aes(x=removenumber/N,y=value))+
  geom_line()+
  facet_wrap(~name,scales = 'free_y')


```

```{r twobubbles}


removenumber2 = seq(0,nl,1000) # this is for two bubbles

g_bubble2=sample_degseq(degseq+rev(degseq))

data.frame(removenumber2)%>% 
  mutate(d=map(removenumber2,~meanmaxClusters(g_bubble2,.))) %>% 
  unnest(d)->tmp_bubble2

tmp_bubble2 %>% 
  pivot_longer(-removenumber2) %>% 
  ggplot(aes(x=removenumber2/N,y=value))+
  geom_line()+
  facet_wrap(~name,scales = 'free_y')



```


```{r}

theoreticalPC = function(degseq){
  
  meank = mean(degseq)
  mean2k = mean(degseq*degseq)
  
  theopc = meank/(mean2k-meank)
  return(theopc)
}

N=100000

# write wrapper function

find_threshold<-function(degree_dist_p,N){
  
  # === no bubbles
  degseq=1
  while(sum(degseq)%%2!=0)sample(30, N, replace = TRUE, degree_dist_p)->degseq # generate sequence
  
  mean(degseq)
  theoreticalPC(degseq)
  
  performPercolationAnalysis(degseq) %>% 
     mutate(Type='No-bubbles')->tmp
  
 # ===  join up bubbles of size 2.

  degseq_2bubbles = degseq+rev(degseq)
  
  mean(degseq_2bubbles)
  theoreticalPC(degseq_2bubbles)  
  
  performPercolationAnalysis(degseq_2bubbles) %>% 
        mutate(Type='2-bubbles')->tmp2
  

  # === join up bubbles of size 3  
  
  degseq2=1
  while(sum(degseq2)%%2!=0)sample(30, N, replace = TRUE, degree_dist_p)->degseq2 # generate sequence
  
  degseq_3bubbles = degseq+rev(degseq)+degseq2
  mean(degseq_3bubbles)
  theoreticalPC(degseq_3bubbles)
  
  performPercolationAnalysis(degseq_3bubbles) %>% 
    mutate(Type='3-bubbles')->tmp3
    
  
  # ===  1-add-1 (2 become 1)
   
  degree_dist_p_mod=degree_dist_p # copy the distribution
  degree_dist_p_mod[2]=degree_dist_p_mod[2]+degree_dist_p_mod[1]/2 # move all hh of size 1 to hh of size 2
  degree_dist_p_mod[1]=0 # remove all housholds of size 1
  degree_dist_p_mod=degree_dist_p_mod/sum(degree_dist_p_mod)  # 
  
  degseq3=1
  while(sum(degseq3)%%2!=0)sample(30, N, replace = TRUE, degree_dist_p_mod)->degseq3 # generate sequence 
  degseq2become1=degseq3
  mean(degseq2become1)
  theoreticalPC(degseq2become1)
  
  performPercolationAnalysis(degseq2become1) %>% 
    mutate(Type = '1+1')->tmp4
  
  
  # ===  1 joins another
  degree_dist_p_noones=degree_dist_p # copy the distribution
  degree_dist_p_noones[1]=0 # remove all housholds of size 1
  degree_dist_p_noones=degree_dist_p_noones/sum(degree_dist_p_noones)  #renormalise distribution
  degseq_noones=1
  while(sum(degseq_noones)%%2!=0)sample(30, N, replace = TRUE, degree_dist_p_noones)->degseq_noones # generate sequence

  mean(degseq_noones)
  theoreticalPC(degseq_noones)
  
  performPercolationAnalysis(degseq_noones) %>% 
    mutate(Type = '1+n')->tmp5

  
  

   # ===  1+2s join another
  degree_dist_p_notwos=degree_dist_p # copy the distribution
  degree_dist_p_notwos[1]=0 # remove all housholds of size 1
  degree_dist_p_notwos[2]=0 # remove all housholds of size 1
  degree_dist_p_notwos=degree_dist_p_notwos/sum(degree_dist_p_notwos)  # renormalise
  
  degseq_notwos=1
  while(sum(degseq_notwos)%%2!=0)sample(30, N, replace = TRUE, degree_dist_p_notwos)->degseq_notwos # generate sequence 
  
  
  mean(degseq_notwos)
  theoreticalPC(degseq_notwos)
  
  performPercolationAnalysis(degseq_notwos) %>% 
    mutate(Type = '2+n')->tmp6
  
  
  
#  save(file = 'DegreeDistribs.Rdata',list = c('degseq','degseq_2bubbles','degseq_3bubbles','degseq2become1','degseq_noones','degseq_notwos'))
  
  return(rbind(tmp,tmp2,tmp3,tmp4,tmp5,tmp6))

}

performPercolationAnalysis<-function (degree_sequence){
  
  
  g <- sample_degseq(degree_sequence)
#  MeanDegSq = mean(degree(g)^2)

  nl= gsize(g) #count number of links
  removenumber = seq(0,nl,nl/100) # generate vector of number of links to remove. 

  data.frame(removenumber)%>% 
    mutate(d=map(removenumber,~meanmaxClusters(g,.))) %>% 
    unnest(d) %>% 
    mutate(LinksPerHousehold = (nl-removenumber)/nl) %>% 
    mutate(MeanDegSq)->tmp
  
  return(tmp)
}

find_threshold(degree_dist_p,N)->tmp

plan(multisession,workers=6)

data.frame (rep = seq(300))%>% 
  mutate(tmp = future_map(rep,~find_threshold(degree_dist_p,N)))->tmp2
```




```{r}


tmp2 %>% 
  unnest(cols = c(tmp)) %>% 
  group_by(Type,removenumber) %>% 
  summarise(MMax = mean(Max,na.rm = T),
            `Mean Component Size`=mean(Mean_woMax,na.rm = T),LinksPerHousehold=mean(LinksPerHousehold,na.rm = T)) %>% 
  mutate(`Giant Component`=MMax/N) %>% 
  pivot_longer(cols=c(`Giant Component`,`Mean Component Size`)) %>% 
#  mutate(proplinks=1/proplinks) %>% 
  ggplot(aes(x=LinksPerHousehold,y=(value),colour=Type))+
  geom_line(size=1.5,alpha=0.7)+
  geom_vline(xintercept = 0.5,linetype="dotted")+
  annotate("rect", xmin = c(0.6*0.5), 
           xmax = c(0.9*0.5),
           ymin = 0, ymax = Inf,
           alpha = 0.2, 
           fill = c("blue"))+
  #geom_vline(xintercept = 0.5*0.7,linetype="dotted",colour='red')+
#  facet_grid(Type~.,scales = 'free_x')+
  xlab('Average links per person outside household')+
  ylab(' ')+
  labs(color='Bubbling strategy')+
  facet_grid(name~.,scale='free_y')+
  theme_minimal_grid()+
  panel_border()->p

ggsave(p,filename = 'Combined.png',width=8,height=9)
library(plotly)
ggplotly(p)
```



```{r}


tmp2 %>% 
  unnest(cols = c(tmp)) %>% 
  group_by(Type,removenumber) %>% 
  summarise(MMax = mean(Max,na.rm = T),`Mean Component Size`=mean(Mean_woMax,na.rm = T),LinksPerHousehold=mean(LinksPerHousehold,na.rm = T)) %>% 
  mutate(`Giant Component`=MMax/N)%>% 
  group_by(Type)%>% 
  filter(`Mean Component Size`==which.max(`Mean Component Size`))


```



```{r}

tmp2 %>% 
  unnest(cols = c(tmp)) %>% 
  group_by(Type,removenumber) %>% 
  summarise(MMax = mean(Max,na.rm = T),
            `Mean Component Size`=mean(Mean_woMax,na.rm = T),LinksPerHousehold=mean(LinksPerHousehold,na.rm = T)) %>% 
  mutate(`Giant Component`=MMax/N) %>% 
  pivot_longer(cols=c(`Giant Component`,`Mean Component Size`)) %>% 
#  mutate(proplinks=1/proplinks) %>% 
  ggplot(aes(x=LinksPerHousehold,y=(value),colour=Type))+
  geom_line(size=1.5,alpha=0.7)+
#  geom_vline(xintercept = 0.5,linetype="dotted")+
#  geom_vline(xintercept = 0.35,linetype="dotted",colour='red')+
#  facet_grid(Type~.,scales = 'free_x')+
  xlab('Average links per person outside household')+
  ylab(' ')+
  xlim(0,0.75)+
  labs(color='Bubbling scenario')+
  facet_grid(name~.,scale='free_y')+
  theme_minimal_grid()+
  panel_border()
  




```

```{r}
tmp %>% 
  select(LinksPerHousehold,Max,Mean_woMax,SD,Type) %>% 
#  mutate(proplinks=1/proplinks) %>% 
  ggplot(aes(x=LinksPerHousehold,y=Max/N,colour=Type))+
  geom_line(size=1.5,alpha=0.7)+
  geom_vline(xintercept = 0.5,linetype="dotted")+
  xlab('Average links per person outside household')+
  ylab('Proportion of housholds in the giant component')+
  labs(color='Bubbling strategy')+
  theme_minimal_grid()->p



ggsave(p,filename = 'GiantComponentSize.png',width=7,height=5)

```



```{r}

tmp %>% 
  select(LinksPerHousehold,Max,`Mean Component Size`=Mean_woMax,Type)%>% 
  mutate(`Giant Component`=Max/N) %>% 
  pivot_longer(cols=c(`Giant Component`,`Mean Component Size`))%>% 
#  mutate(proplinks=1/proplinks) %>% 
  ggplot(aes(x=LinksPerHousehold,y=value,colour=Type))+
  geom_line(size=1.5,alpha=0.7)+
  geom_vline(xintercept = 0.5,linetype="dotted")+
#  facet_grid(Type~.,scales = 'free_x')+
  xlab('Average links per person outside household')+
  ylab(' ')+
  labs(color='Bubbling strategy')+
  facet_grid(name~.,scale='free_y')+
  theme_minimal_grid()


tmp %>% filter(LinksPerHousehold==0.5)
  
```


```{r}

tmp %>% 
  select(LinksPerHousehold,Max,Mean_woMax,SD,Type) %>% 
#  mutate(proplinks=1/proplinks) %>% 
  ggplot(aes(x=LinksPerHousehold,y=Mean_woMax,colour=Type))+
    geom_line(size=1.5,alpha=0.7)+
#  facet_grid(Type~.,scales = 'free_x')+
  xlab('Average links per person outside household')+
  ylab('Mean component size')+
  labs(color='Bubbling strategy')+
  theme_minimal_grid()->p

ggsave(p,filename = 'OrderParameter.png',width=7,height=5)


tmp %>% 
  group_by(Type) %>% 
  summarise(24+which.max(Mean_woMax[25:100]))
  

```

```{r}
library('tidygraph')
library('ggraph')
E(tenK_g)
tenK_g %>% 
    ggraph(layout = 'kk')+
    geom_edge_link() + 
    geom_node_point(size = 8, colour = 'steelblue') +
    geom_node_text(aes(label = name), colour = 'white', vjust = 0.4) + 
    ggtitle('Binding graphs') + 
    theme_graph()



```


```{r}
library(ggraph)
g<-bind_graphs(create_complete(2),create_complete(3),create_complete(5))

g %>% ggraph(layout='kk') +
  geom_edge_link() + 
  geom_node_point(size = 8, colour = 'steelblue')


play_islands(n_islands = 5, size_islands = c(5), 1, 1) %>% 
    mutate(community = as.factor(group_infomap())) %>% 
    ggraph(layout = 'kk') + 
    geom_edge_link(aes(alpha = ..index..), show.legend = FALSE) + 
    geom_node_point(aes(colour = community), size = 7) + 
    theme_graph()
```

```{r}

sizes=c(2,3,4,5)
n=sum(sizes)
pmatrix=diag(length(sizes))




play_blocks(sum(sizes),p_between=pmatrix+0.03,sizes) %>% 
   mutate(community = as.factor(group_infomap())) %>% 
    ggraph(layout = 'kk') + 
    geom_edge_link(aes(alpha = ..index..), show.legend = FALSE) + 
    geom_node_point(aes(colour = community), size = 7) + 
    theme_graph()

ll=data.frame(from =c(1,3,1,4,3,2,2,4),
              to =  c(3,1,4,1,2,3,4,2))

as_tbl_graph(ll) %>% 
  ggraph(layout = 'fr') + 
    geom_edge_link(aes(alpha = ..index..), show.legend = FALSE) + 
    geom_node_point(aes(colour = name), size = 7) + 
    theme_graph()


```




```{r generate degree sequence}


prop_def_bubbling = 0.33 # 33% definitely forming a bubble, 8% probably will
prop_def_bubbling = 0.33+0.08+0.09  # 9% don't know
prop_probably_bubbling = 0.08
prop_def_not_bubbling = 0.25   # 25% definitely not forming a bubble, 13% probably wont. 
prop_probably_not_bubbling = 0.13

bubblesizes=c(0.35, 0.31, 0.09, 0.03, 0.01,0.01) #21% don't know - assume they follow a similar distribution

bubblesizes = bubblesizes/sum(bubblesizes)

prop_bubbling = c(1-prop_def_bubbling,prop_def_bubbling*bubblesizes)

sum(prop_bubbling)

generatedegseq<-function(degree_dist_p,N,prop_bubbling){
  
    degseq=1
    while(sum(degseq)%%2!=0){
      
      if(prop_bubbling[1]>0){
      # generate a vector of household sizes from HH distribution
        sample(30, round(N*prop_bubbling[1]), replace = TRUE, degree_dist_p)->degseq1 #sample with replacement 
      }
    
      if(prop_bubbling[2]>0){
      # generate a smaller vector of 2 bubbles
        sample(30, round(N*prop_bubbling[2]/2), replace = TRUE, degree_dist_p)->degseq_2_tmp 
        degseq2 = degseq_2_tmp + rev(degseq_2_tmp)# now make a vector of the right size of the right characteristics
      }
    
      if(prop_bubbling[3]>0){
      # generate a vector of 3 bubbles    
        sample(30, round(N*prop_bubbling[3]/3), replace = TRUE, degree_dist_p)->degseq_3_tmp
        sample(30, round(N*prop_bubbling[3]/3), replace = TRUE, degree_dist_p)->degseq_3_tmp2
        degseq3 = degseq_3_tmp + rev(degseq_3_tmp) + degseq_3_tmp2
      }
      if(prop_bubbling[4]>0){
      # generate a vector of 4 bubbles    
        sample(30, round(N*prop_bubbling[4]/4), replace = TRUE, degree_dist_p)->degseq_4_tmp
        sample(30, round(N*prop_bubbling[4]/4), replace = TRUE, degree_dist_p)->degseq_4_tmp2
        degseq4 = degseq_4_tmp + rev(degseq_4_tmp) + degseq_4_tmp2 + rev(degseq_4_tmp2)
      }
      
      if(prop_bubbling[5]>0){
      # generate a vector of 5 bubbles    
        sample(30, round(N*prop_bubbling[5]/5), replace = TRUE, degree_dist_p)->degseq_5_tmp
        sample(30, round(N*prop_bubbling[5]/5), replace = TRUE, degree_dist_p)->degseq_5_tmp2
        sample(30, round(N*prop_bubbling[5]/5), replace = TRUE, degree_dist_p)->degseq_5_tmp3
        degseq5 = degseq_5_tmp + rev(degseq_5_tmp) + degseq_5_tmp2 + rev(degseq_5_tmp2) + degseq_5_tmp3
      }
    
      degseq=c(degseq1,degseq2,degseq3,degseq4,degseq5)
    }
return(degseq)
}

#degseq+rev(degseq)+degseq2


#while(sum(degseq_noones)%%2!=0)sample(30, N, replace = TRUE, 
 #                                     degree_dist_p_noones)->degseq_noones # generate sequence

#while(sum(degseq)%%2!=0)sample(30, N, replace = TRUE, degree_dist_p)->degseq 

```

```{r}

get_bubble_result<-function(degree_dist_p,N){
  #proportion of respondents who said they'd bubble by bubble size: 2,3,4,5,6,7+
  bubblesizes=c(0.35, 0.31, 0.09, 0.03, 0.01,0.01) #21% don't know - assume they follow a similar distribution
  bubblesizes = bubblesizes/sum(bubblesizes)
  
  #best case: only those that said they'd DEFINITELY bubble actually do
  prop_def_bubbling = 0.33 # 33% definitely forming a bubble, 8% probably will
  prop_bubbling = c(1-prop_def_bubbling,prop_def_bubbling*bubblesizes)
  bestcase=generatedegseq(degree_dist_p,N,prop_bubbling)
  
  mean(bestcase)
  theoreticalPC(bestcase)
  
  performPercolationAnalysis(bestcase) %>% mutate(Type = 'BestCase') -> bestcase_results
  
  
  
  #reasonable case: definitely and probably bubble
  prop_def_bubbling = 0.33+0.08 + 0.09*(0.08+0.33)
  #prop_def_bubbling = prop_def_bubbling*1.09 #assume 33%+8%=41% of the don't knows (9%) decide to bubble
  prop_bubbling = c(1-prop_def_bubbling,prop_def_bubbling*bubblesizes)
  reasonablecase=generatedegseq(degree_dist_p,N,prop_bubbling)
  mean(reasonablecase)
  theoreticalPC(reasonablecase)
  
  performPercolationAnalysis(reasonablecase) %>% mutate(Type = 'ReasonableCase') -> reasonablecase_results
  
  #worst case
  prop_def_bubbling = 1-0.25 #1 minus the prop definitely NOT bubbling
  prop_bubbling = c(1-prop_def_bubbling,prop_def_bubbling*bubblesizes)
  worstcase=generatedegseq(degree_dist_p,N,prop_bubbling)
  mean(worstcase)
  theoreticalPC(worstcase)
  performPercolationAnalysis(worstcase) %>% mutate(Type = 'WorstCase') -> worstcase_results
  
  #impact of big bubbles
  # proportion of respondents who said they'd bubble by bubble size: 2,3,4,5,6,7+
  
  bubblesizes2=c(0.35, 0.31, 1e-10, 1e-10, 1e-10,1e-10) #21% don't know - assume they follow a similar distribution
  bubblesizes2 = bubblesizes2/sum(bubblesizes2)
  prop_def_bubbling = 0.33+0.08 + 0.09*(0.08+0.33)
  # prop_def_bubbling = prop_def_bubbling*1.09 #assume 33%+8%=41% of the don't knows (9%) decide to bubble
  prop_bubbling = c(1-prop_def_bubbling,prop_def_bubbling*bubblesizes2)
  nolargebubbles=generatedegseq(degree_dist_p,N,prop_bubbling)
  
  #performPercolationAnalysis(nolargebubbles) %>% mutate(Type = 'Max3') -> nolargebubbles_results--commented out for speed
  
  
  #results = rbind(bestcase_results,reasonablecase_results,worstcase_results,nolargebubbles_results)
#  save(file = 'DegreeDistribsXmas.Rdata',list = c('bestcase','reasonablecase','worstcase'))
  results = rbind(bestcase_results,reasonablecase_results,worstcase_results)
  
  return(results)
}

data.frame (rep = seq(300))%>% 
  mutate(tmp = future_map(rep,~get_bubble_result(degree_dist_p,N)))->results_reps2
```

```{r include = FALSE}
# Testing plotting 

results %>% 
  select(LinksPerHousehold,Max,Mean_woMax,SD,Type)%>% 
#  mutate(proplinks=1/proplinks) %>% 
  ggplot(aes(x=LinksPerHousehold,y=Mean_woMax,,colour = Type))+
    geom_line(size=1.5,alpha=0.7)+
#  facet_grid(Type~.,scales = 'free_x')+
  xlab('Average links per person outside household')+
  ylab('Mean component size')+
  labs(color='Bubbling scenario')+
    annotate("rect", xmin = c(0.6*0.5), 
           xmax = c(0.9*0.5),
           ymin = 0, ymax = Inf,
           alpha = 0.2, 
           fill = c("blue"))+
  theme_minimal_grid()+
  xlim(0.0,0.8)+
  ylim(1,2.5)->p

library(plotly)
ggplotly(p)
```




```{r}
  
library(patchwork)

results_reps = results_reps2

results_reps %>% 
  unnest(cols = c(tmp)) %>% 
  #filter(LinksPerHousehold<0.75) %>% 
  ggplot(aes(x = LinksPerHousehold,
             y = Mean_woMax,
             group = interaction(Type,rep),
             colour = Type))+
  geom_line(alpha = 0.2)+
    theme_minimal_grid()+
    theme(legend.position = '')+
  xlim(0.0,0.8)+
  ylim(1,2.5)+  
  xlab('Average links per person outside household')+
  ylab('Mean component size')-> op


results_reps %>% 
  unnest(cols = c(tmp)) %>% 
  group_by(Type,rep) %>% 
  mutate(Giant = Max/max(Max)) %>% 
#  filter(LinksPerHousehold<0.75) %>% 
  ggplot(aes(x = LinksPerHousehold,
             y = Giant,
             group = interaction(Type,rep),
             colour = Type))+
  geom_line(alpha = 0.2)+
  theme_minimal_grid()+
  theme(legend.position = '')+
  xlim(0.0,0.8)+
  #ylim(1,2.5)+  
  xlab('')+
  ylab('Giant component size')-> g



results_reps %>% 
  unnest(cols = c(tmp)) %>% 
  filter(LinksPerHousehold<0.75) %>% 
  group_by(rep,Type) %>% 
  filter(Mean_woMax == max(Mean_woMax,na.rm=T)) %>% 
  arrange(Type,rep) %>% 
  ungroup() %>% 
  ggplot(aes(x=Type,y=LinksPerHousehold,fill=Type,colour = Type))+
  geom_violin(adjust = 3)+
  ylab('Percolation threshold')+
  theme_minimal_grid()+
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = -30))+
  xlab('')-> s
  


results_reps %>% 
  unnest(cols = c(tmp)) %>% 
  filter(LinksPerHousehold<0.75) %>% 
  group_by(rep,Type) %>% 
  filter(Mean_woMax == max(Mean_woMax,na.rm=T)) %>% 
  arrange(Type,rep) %>% 
  ungroup() %>% 
  group_by(Type) %>%
  summarise(MeanThreshold = mean(LinksPerHousehold),
            Upper = quantile(LinksPerHousehold,0.975),
            Lower = quantile(LinksPerHousehold,0.025))


(g / op) |  s ->f

f+plot_annotation(tag_levels = 'A') &
  theme(plot.tag = element_text(size = 18))->f

ggsave(f,filename = 'XmasBubbles.png',width=9,height=7)
```

```{r}
# Original bubbles re-draw figure

tmp2 %>% 
  unnest(cols = c(tmp)) %>% 
  #filter(LinksPerHousehold<0.75) %>% 
  ggplot(aes(x = LinksPerHousehold,
             y = Mean_woMax,
             group = interaction(Type,rep),
             colour = Type))+
  geom_line(alpha = 0.2)+
    theme_minimal_grid()+
    theme(legend.position = '')+
  xlim(0.0,0.8)+
  ylim(1,3)+  
  xlab('Average links per person outside household')+
  ylab('Mean component size')-> op_orig


tmp2 %>% 
  unnest(cols = c(tmp)) %>% 
  group_by(Type,rep) %>% 
  mutate(Giant = Max/max(Max)) %>% 
#  filter(LinksPerHousehold<0.75) %>% 
  ggplot(aes(x = LinksPerHousehold,
             y = Giant,
             group = interaction(Type,rep),
             colour = Type))+
  geom_line(alpha = 0.2)+
  theme_minimal_grid()+
  theme(legend.position = '')+
  xlim(0.0,0.8)+
  #ylim(1,2.5)+  
  xlab('')+
  ylab('Giant component size')-> g_orig



tmp2 %>% 
  unnest(cols = c(tmp)) %>% 
  filter(LinksPerHousehold<0.75) %>% 
  group_by(rep,Type) %>% 
  filter(Mean_woMax == max(Mean_woMax,na.rm=T)) %>% 
  arrange(Type,rep) %>% 
  ungroup() %>% 
  ggplot(aes(x= reorder(Type, 
                        -LinksPerHousehold, 
                        FUN = median),
             y=LinksPerHousehold,
             fill=Type,colour = Type))+
  geom_boxplot()+
#  geom_violin(adjust = 3)+
  ylab('Percolation threshold')+
  theme_minimal_grid()+
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = -90))+
  xlab('')-> s_orig


#results_reps %>% 
#  unnest(cols = c(tmp)) %>% 
#  filter(LinksPerHousehold<0.75) %>% 
#  group_by(rep,Type) %>% 
#  filter(Mean_woMax == max(Mean_woMax,na.rm=T)) %>% 
#  arrange(Type,rep) %>% 
#  ungroup() %>% 
#  group_by(Type) %>%
#  summarise(MeanThreshold = mean(LinksPerHousehold),
#            Upper = quantile(LinksPerHousehold,0.975),
#            Lower = quantile(LinksPerHousehold,0.025))


(g_orig / op_orig) |  s_orig ->f_orig

f_orig+plot_annotation(tag_levels = 'A') &
  theme(plot.tag = element_text(size = 18))->f_orig

ggsave(f_orig,filename = 'OriginalBubbles.png',width=9,height=7)

```

```{r}
tmp2 %>% 
  unnest(cols = c(tmp)) %>% 
  filter(LinksPerHousehold<0.75) %>% 
  group_by(rep,Type) %>% 
  filter(Mean_woMax == max(Mean_woMax,na.rm=T)) %>% 
  arrange(Type,rep) %>% 
  ungroup()->perc_thresh_orig

results_reps %>% 
  unnest(cols = c(tmp)) %>% 
  filter(LinksPerHousehold<0.75) %>% 
  group_by(rep,Type) %>% 
  filter(Mean_woMax == max(Mean_woMax,na.rm=T)) %>% 
  arrange(Type,rep) %>% 
  ungroup() -> perc_thresh_xmas

rbind(perc_thresh_orig,perc_thresh_xmas)%>% 
  ggplot(aes(x= reorder(Type, 
                        -LinksPerHousehold, 
                        FUN = median),
             y=LinksPerHousehold,
             fill=Type,colour = Type))+
  geom_boxplot()+
#  geom_violin(adjust = 3)+
  ylab('Percolation threshold')+
  theme_minimal_grid()+
  theme(legend.position = '',
        axis.text.x = element_text(angle = -90))+
  xlab('')+
  ylim(0.03,0.55)->alltogethernow

ggsave(alltogethernow,filename='AllBubblesThresholds.png',width=6,height=4)


```


```{r}
### Calculation of Household Reproduction number Rh (Table 2)

load("DegreeDistribs.Rdata")
load("DegreeDistribsXmas.Rdata")

# From Lopez Barnal 2020 https://doi.org/10.1101/2020.08.19.20177188
HH1=c(2,3,4,5)
Smean=c(0.49,0.41,0.32,0.25) 
Slo=c(0.37,0.29,0.22,0.14)#95% CI
Shi=c(0.6,0.52,0.42,0.36)
#legend('topleft',c("no bubbles","2-bubbles",'3-bubbles','1+n',"BPC","RPC","WPC"),col=mycols[c(1,2,3,5,7,8,9)],pch=15,pt.cex=1.5,cex=1.2)

#Pc
#baseline 0.48
#2-bubbles 0.23
#3-bubbles 0.15
#2become1 0.44
#noones 0.41
#notwos 0.33
#best 0.30
#reasonable 0.26
#worstcase 0.19
pc=c(0.48,0.23,0.15,0.41,0.33,0.44,0.30,0.26,0.19)

allmodelout = data.frame(degseq=c(degseq,degseq_2bubbles,degseq_3bubbles,degseq_noones,degseq_notwos,degseq2become1,bestcase,reasonablecase,worstcase),
           strategy = c(rep(c("baseline","2bubbles","3bubbles","noones","notwos","2become1"),each=length(degseq)),
                        rep("bestcase",length(bestcase)),rep("reasonablecase",length(reasonablecase)),rep("worstcase",length(worstcase))),
           secondarycases = rep(0,length(degseq)*6 + length(bestcase)+length(reasonablecase)+length(worstcase)),
           pthreshold = c(rep(pc[1:6],each=length(degseq)),rep(pc[7],length(bestcase)),rep(pc[8],length(reasonablecase)),rep(pc[9],length(worstcase))))


for(i in 1:max(allmodelout$degseq))
{
  ix = allmodelout$degseq==i
  if(i==1)
  {
    allmodelout$secondarycases[ix] = rep(0,sum(ix))
  }
  else if(i>4)
  {
    allmodelout$secondarycases[ix] = rbinom(sum(ix),size=i,prob=Smean[5-1])
  }
  else{
    allmodelout$secondarycases[ix] = rbinom(sum(ix),size=i,prob=Smean[i-1])
  }
}



# allmodelout %>%
#   mutate(Rh = secondarycases*pthreshold) %>%
#   ggplot(aes(x=strategy,y=Rh,fill=strategy)) +
#   geom_boxplot()
# 
# 
# allmodelout %>%
#   mutate(R0 = secondarycases*1) %>%
#   ggplot(aes(x=strategy,y=R0,fill=strategy)) +
#   geom_boxplot(outlier.shape = NA) + 
#   scale_y_continuous(limits = c(0,7))
  

allmodelout %>%
  group_by(strategy) %>%
  summarise(HouseholdR=mean(secondarycases),CI25=quantile(secondarycases,prob=0.25),CI75=quantile(secondarycases,prob=0.75))


```

